### PR TITLE
Fix keybinding for win32

### PR DESCRIPTION
**Pull request by jugglingnutcase**
As of v0.2.1,, the keybinding is gone for me! This should take care of it. i'm wondering if the API changes along with the Shadom DOM stuff switched this?

@cliffrowley, do you want me looking for approval from someone else before pulling my own work in?

### CODE REVIEW

**Comment by jugglingnutcase** [comment]
i can fix the mac keybinding here too if you ask me too.

**Comment by cliffrowley** [comment]
Ah, I figured it was just broken here because Atom uses the same key bind for something else on Mac.  I think perhaps as well as fixing it, we should look at changing the keymap anyway because it conflicts with built in functionality (find previous).  Thoughts?=

**Comment by jugglingnutcase** [comment]
Wasn't aware of that conflict... How about <kbd>Ctrl-Alt-G</kbd>? ("G" for GitHub?) That doesn't seem to be taken on my machine.

**Comment by cliffrowley** [comment]
That works for me here too, the key binding resolver shows nothing for ctrl-alt-g.  Let's go with that and add a note to the release.=

**Comment by jugglingnutcase** [comment]
:warning: Dumb question: what's the equivalent of ctrl-alt-g on the mac? Is there an alt key? i guess i could look at my wife's laptop, but i'll just ask here :smile:

**Comment by cliffrowley** [comment]
It's just ctrl-alt-g ;-)

**Comment by jugglingnutcase** [comment]
Oh... right. i knew that :wink:

**Comment by jugglingnutcase** [comment]
OK, i think that should do it!

**Comment by cliffrowley** [comment]
I'll merge and publish this today - thanks @jugglingnutcase.  I'll also see if I can allow you to publish to amp too (not sure if it's possible?)..

**Comment by jugglingnutcase** [comment]
Thanks for trusting me with that!

I'll do the legwork on finding out if a package can have multiple
publishers and let you know what I find.

**Comment by jugglingnutcase** [comment]
Want me to just try it? i wonder if i already can publish just because i have committer access to this repository...

Or maybe i'm just reading too much into [this comment](https://github.com/atom/apm/issues/188#issuecomment-55323997). The thread in atom/apm#218 seems to imply this too given a bit of overly generous reading between the lines.

**Pull request merged**
