### PR TITLE
Support windows

### PR DESCRIPTION
**Pull request by jugglingnutcase**
Hi @cliffrowley!

Thanks for starting this atom package. i added some stuff to make this package support opening the GitHub for Windows app with the current repository. It's still a little rough, but the basics work. i changed some code, so i'm sorry to say you may have to test it out to make sure i didn't break the mac stuff... i tried not to!

I saw your comment on tests in the spec folder, I hope to add some tests in the near future. i can do that here or in a separate PR, let me know (if i don't get to it before you can comment).

### CODE REVIEW

**Comment by laedit** [comment]
:+1:  for this, I wanted to create a package but this will do the trick.
I can help for testing :smiley:

**Comment by jugglingnutcase** [comment]
If you want to add tests, feel free to PR off my PR!

**Comment by cliffrowley** [comment]
I'm really sorry, I'm such a douche and I've neglected this of late.. Thanks for reminding me!

**Comment by jugglingnutcase** [comment]
@cliffrowley i don't feel like that's what you've been :smile: i've been using my own work for a while so i never felt enough pain to ping you about it.

i mostly am worried i broke something for the mac support since i don't have a mac to test it!

**Comment by cliffrowley** [comment]
@jugglingnutcase if it's OK with you, I'd like to add you as a committer - I don't really use Windows for development so your input on that side would be invaluable, and it seems silly to have to wait for me to get around to it (currently up to my eyeballs!)

**Comment by jugglingnutcase** [comment]
Sure! i thought about asking but didn't want to impose.

**Comment by cliffrowley** [comment]
Done, thanks!

**Comment by jugglingnutcase** [comment]
:warning: i don't have a mac, so if i break anything i'll have a hard time knowing about it!

**Comment by jugglingnutcase** [comment]
Cool! This is the first project of someone else's that i'm a committer on :smile:  thanks! :tada:

**Comment by cliffrowley** [comment]
That's OK, if we maintain a process of testing on both before releasing then it'll be fine.  It doesn't take long to test it's such a tiny piece of functionality :-)

**Comment by jugglingnutcase** [comment]
Yeah, it's pretty easy for me to know if it works or not. The GitHub app either launches to the right place or it doesn't.

**Comment by jugglingnutcase** [comment]
Does that mean i have publish permissions too? i'm guessing not.

**Comment by cliffrowley** [comment]
Exactly.  Do you think its worth maintaining a testing branch that we merge into master when we've both tested?

**Comment by jugglingnutcase** [comment]
(i'm OK not having that, btw)

**Comment by cliffrowley** [comment]
Regarding publishing permissions, not sure - but I'll check

**Comment by cliffrowley** [comment]
(I'll fix the README image too btw, it broke when I switched to personal & work dropbox partition)

**Comment by jugglingnutcase** [comment]
> Do you think its worth maintaining a testing branch that we merge into master when we've both tested?

If you think that's helpful we can do that... i'm hoping to figure out the test to write to detect that a process was shelled out to, i think that's possible, just haven't done the research of how to detect it yet.

**Comment by cliffrowley** [comment]
That'd be good.  I have a capable server here too that I run various CI tests on, I'll see if I can set something rudimentary up.

**Comment by jugglingnutcase** [comment]
We can just use Travis CI and Appveyor. i have them set up on my @jugglingnutcase/language-powershell project and they both work great... no personal CI needed :smile:

**Comment by cliffrowley** [comment]
Even for Mac? ;-)

**Comment by jugglingnutcase** [comment]
Oh right! nm.

**Comment by jugglingnutcase** [comment]
oops, missed the :boat: on that :train: of thought! :wink:

**Comment by cliffrowley** [comment]
Confirmed this is all working fine for me on OS X still

**Comment by jugglingnutcase** [comment]
Awesome!

**Pull request merged**
